# FIXME: Future improvements
# - only run when a new version gets released on the main page
# - produce rpm, deb, and Appimages
# - Auto publish to github releases
# - Setup a fedora copr repo maybe
name: Build Linux Arm64 Packages

on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: super-productivity/super-productivity

      - name: Install npm Packages
        run: npm i

      - run: npm run env # Generate env.generated.ts

      - name: Build Frontend (No tests)
        run: npm run buildAllElectron:noTests:prod

      - name: Build Electron RPM
        run: npx electron-builder --linux rpm --arm64
