name: Build Linux Arm64 Packages

on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: super-productivity/super-productivity

      # work around for npm installs from git+https://github.com/johannesjo/J2M.git
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/

      - name: Install npm Packages
        run: npm i

      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps chromium
          npx playwright install-deps chromium

      - run: npm run env # Generate env.generated.ts

      - name: Build Frontend (No tests)
        run: npm run buildAllElectron:noTests:prod

      - name: Build Electron RPM
        run: npx electron-builder --linux rpm --arm64
