# FIXME: Future improvements
# - auto run when a new version gets released on the main page
# - Setup a fedora copr repo maybe
name: Build Linux Arm64 Packages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          repository: super-productivity/super-productivity

      - name: Extract upstream version
        id: version
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT


      - name: Install npm Packages
        run: npm i

      - run: npm run env # Generate env.generated.ts

      - name: Build Frontend (No tests)
        run: npm run buildAllElectron:noTests:prod

      - name: Build Electron RPM
        run: npx electron-builder --linux rpm deb AppImage --arm64 --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Github Release
        uses: ncipollo/release-action@v1 
        with:
          artifacts: ./.tmp/app-builds/*.rpm, ./.tmp/app-builds/*.deb, ./.tmp/app-builds/*.AppImage
          tag: ${{ steps.version.outputs.version }}
          skipIfReleaseExists: true
